server:
  port: 8080
spring:
   application:
      name: customer
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761
#   datasource:
#      url: 'jdbc:postgresql://localhost:5432/customer'
#      username: 'postgres'
#      password: 'Sandanskii1995*'
#   jpa:
#      hibernate:
#         ddl-auto: update
#      properties:
#         hibernate:
#          dialect: org.hibernate.dialect.PostgreSQLDialect
#          format_sql: 'true'
#          non_contextual_creation: 'true'
#      show-sql: true